######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 6 15:28:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MyThread.h
SOURCES += main.cpp MainWindow.cpp MyThread.cpp
