######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 16 10:46:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cralwer.h
FORMS += cralwer.ui
SOURCES += cralwer.cpp main.cpp
