######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 20 14:46:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network
# Input
SOURCES += downloader.cpp
